# -*- coding: utf-8 -*-
from zope.interface import implementer, Interface
from schematics.types import StringType
from schematics.transforms import whitelist, blacklist
from openprocurement.contracting.core.models import (
    contract_view_role,
    contract_create_role,
    Contract as BaseContract
)


class ICommonContract(Interface):
    """ Contract marker interface """


@implementer(ICommonContract)
class Contract(BaseContract):
    """ Common Contract """

    class Options:
        roles = {
            'create': contract_create_role + whitelist('contractType'),
            'view': contract_view_role + whitelist('contractType'),
        }

    # BBB not required for 'old' contracts
    # new contract will have this field generated by databridge
    contractType = StringType(required=False, choices=['common'])
